Gp/litecoin
cryptape/ckb-auth pull request #12
Opened 2023-06-06 02:03 UTC by gpBlockchain

2023-06-08 06:49 UTC, XuJiandong requested changes

2023-06-08 06:49 UTC, XuJiandong commented on .github/workflows/doc.yml
> +name: Doc Test
This CI is not necessary.

2023-06-08 07:05 UTC, gpBlockchain commented on .github/workflows/doc.yml
> +name: Doc Test
remove it

2023-06-12 05:26 UTC, XuJiandong commented
out of date. closed.

2023-06-12 05:26 UTC, closed without merging